// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv6rZsHY9-XU9wIWj1oxf_Mfy7oYZ67wY',
    appId: '1:118600507484:web:2043db77cb47bcd79ec699',
    messagingSenderId: '118600507484',
    projectId: 'e-commece-37db4',
    authDomain: 'e-commece-37db4.firebaseapp.com',
    storageBucket: 'e-commece-37db4.appspot.com',
    measurementId: 'G-VRJ21ZWT0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiEfzXZprEwoMU_A0yHtu3bdr5MUiLvF4',
    appId: '1:118600507484:android:08a4a7bbf8eb32e59ec699',
    messagingSenderId: '118600507484',
    projectId: 'e-commece-37db4',
    storageBucket: 'e-commece-37db4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1OElgSVvv6p9r94Vf9JeV0jt-Zd6WkFY',
    appId: '1:118600507484:ios:714033fe4ecb512c9ec699',
    messagingSenderId: '118600507484',
    projectId: 'e-commece-37db4',
    storageBucket: 'e-commece-37db4.appspot.com',
    iosClientId: '118600507484-g6r78hh5hgefqpteq4gulhvn7o4gu2q3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1OElgSVvv6p9r94Vf9JeV0jt-Zd6WkFY',
    appId: '1:118600507484:ios:714033fe4ecb512c9ec699',
    messagingSenderId: '118600507484',
    projectId: 'e-commece-37db4',
    storageBucket: 'e-commece-37db4.appspot.com',
    iosClientId: '118600507484-g6r78hh5hgefqpteq4gulhvn7o4gu2q3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication3',
  );
}
